# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: java:8

pipelines:
  default:
    - step:
        name: Build and Upload to s3
        caches:
          - gradle
        script: # Modify the commands below to build your repository.
          # You must commit the Gradle wrapper to your repository
          # https://docs.gradle.org/current/userguide/gradle_wrapper.html
          - apt-get update
          - apt-get install -y python-dev zip
          - git config --global user.email "deploy@vm-digital.asia"
          - git config --global user.name "Deploy Vmd"
          - bash ./gradlew release -Prelease.useAutomaticVersion=true
          - git describe --tags $(git rev-list --tags --max-count=1) >> version.txt
          - zip -j /tmp/artifact.zip build/libs/* # package up the application for deployment
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install boto3==1.3.0
          - python aws_deploy/upload_to_s3.py # run the deployment script
          - python aws_deploy/create_app_version.py
    - step:
        name: Deploy Dev
        script:
          - apt-get update
          - apt-get install -y python-dev zip
          - git describe --tags $(git rev-list --tags --max-count=1) >> version.txt
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install boto3==1.3.0
          - python aws_deploy/deploy_dev.py
